on:
  pull_request:
name: CI
jobs:
  packages:
    name: Package sanity tests
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Hermit
        run: |
          set -e
          set -o pipefail
          curl -fsSL https://github.com/cashapp/hermit/releases/download/stable/install.sh | bash
      - name: Changed files
        uses: jitterbit/get-changed-files@v1
      - name: Test packages
        run: |
          set -xe -o pipefail
          mkdir build testenv
          ~/bin/hermit validate "file://$PWD"
          ~/bin/hermit init --sources="file://$PWD" ./testenv
          . ./testenv/bin/activate-hermit
          echo "${{ steps.files.outputs.all }}"
          for pkg in $(echo ${{ steps.files.outputs.all }} | tr ' ' '\n' | fgrep .hcl | cut -d. -f1 | xargs -n1 hermit search -s | grep -v '@'); do echo $pkg; hermit test -t $pkg; hermit clean -tp; done
